# Generated by Django 6.1 on 2026-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_book_rating_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], max_length=10, null=True),
        ),
    ]
