# Generated by Django 6.1 on 2026-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_alter_book_rating_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], default='ongoing', max_length=10),
        ),
    ]
